name: Deploy

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Sphinx dependencies
      run: |
        pip install --upgrade pip
        pip install -r docs/requirements.txt
      shell: bash

    - name: Build docs
      run: cd docs && sphinx-build -b html src _build
      shell: bash

    - name: Install Jupyter Lite
      run: pip install --pre jupyterlite
      shell: bash

    - name: Build JupyterLite
      run: |
        mkdir -p docs/_build/_extra/
        mkdir _dist/
        jupyter lite build --contents ./jupyterlite/ --output-dir=./_dist/
        mv ./_dist/* docs/_build/_extra/
      shell: bash

    - uses: shallwefootball/s3-upload-action@master
      with:
        aws_key_id: ${{ secrets.PALEWIRE_DOCS_AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.PALEWIRE_DOCS_AWS_SECRET_ACCESS_KEY }}
        aws_bucket: ${{ secrets.PALEWIRE_DOCS_AWS_BUCKET }}
        source_dir: docs/_build/
        destination_dir: first-python-notebook
