name: "Build documentation"
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  docs:
    name: "Build and deploy"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
        build-command: "sphinx-build -b html src _build"

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Jupyter Lite
      run: pip install --pre jupyterlite
      shell: bash

    - name: Build Jupyter Lite
      run: pipenv run jupyter lite build --contents notebooks
      shell: bash

    - name: Copy Jupyter Lite into Sphinx build
      run: mv _output docs/_build/_extra
      shell: bash

    - uses: actions/upload-artifact@v3
      with:
        name: documentation-html
        path: docs/_build/

    - uses: shallwefootball/s3-upload-action@master
      with:
        aws_key_id: ${{ secrets.PALEWIRE_DOCS_AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.PALEWIRE_DOCS_AWS_SECRET_ACCESS_KEY }}
        aws_bucket: ${{ secrets.PALEWIRE_DOCS_AWS_BUCKET }}
        source_dir: docs/_build/
        destination_dir: first-python-notebook
