name: "Build documentation"
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  docs:
    name: "Build and deploy"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Sphinx dependencies
      run: |
        pip install --upgrade pip
        pip install -r docs/requirements.txt
      shell: bash

    - name: Build docs
      run: cd docs && sphinx-build -b html src _build
      shell: bash

    - name: Install Jupyter Lite
      run: pip install --pre jupyterlite
      shell: bash

    - name: Build Jupyter Lite
      run: |
        jupyter lite build --contents ./jupyterlite/fast-python-notebook
        jupyter lite build --contents ./jupyterlite/stanford-fall-2022
      shell: bash

    - name: Copy Jupyter Lite into Sphinx build
      run: |
        mkdir -p docs/_build/_extra/
        mv _output docs/_build/_extra/fast-python-notebook
        mv _output docs/_build/_extra/stanford-fall-2022
      shell: bash

    - uses: shallwefootball/s3-upload-action@master
      with:
        aws_key_id: ${{ secrets.PALEWIRE_DOCS_AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.PALEWIRE_DOCS_AWS_SECRET_ACCESS_KEY }}
        aws_bucket: ${{ secrets.PALEWIRE_DOCS_AWS_BUCKET }}
        source_dir: docs/_build/
        destination_dir: first-python-notebook
