name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Upgrade pip
      run: pip install --upgrade pip

    - name: Install Python requirements
      run: pip install -r docs/requirements.txt

    - name: Build Sphinx site
      run: cd docs && sphinx-build -b html src _build

    - name: Install Jupyterlite
      run: pip install --pre jupyterlite

    - name: Build Jupyterlite notebooks
      run: |
        mkdir -p docs/_build/_extra/
        mkdir _dist/
        jupyter lite build --contents ./jupyterlite/ --output-dir=./_dist/
        mv ./_dist/* docs/_build/_extra/

    - name: Upload release candidate
      uses: actions/upload-artifact@v3
      with:
        name: release-candidate
        path: ./docs/